import os

RUTA_MAGIZOOLOGOS = os.path.join("magizoologos.csv")
RUTA_CRIATURAS = os.path.join("criaturas.csv")

SICKLES_INICIAL = 500

NIVEL_APROB_MAX = 100
NIVEL_APROB_MIN = 0

NIVEL_MAGICO_DOCENCIO_MIN = 40
NIVEL_MAGICO_DOCENCIO_MAX = 60
NIVEL_MAGICO_TAREO_MIN = 40
NIVEL_MAGICO_TAREO_MAX = 55
NIVEL_MAGICO_HIBRIDO_MIN = 35
NIVEL_MAGICO_HIBRIDO_MAX = 45
DESTREZA_DOCENCIO_MIN = 30
DESTREZA_DOCENCIO_MAX = 40
DESTREZA_TAREO_MIN = 40
DESTREZA_TAREO_MAX = 50
DESTREZA_HIBRIDO_MIN = 30
DESTREZA_HIBRIDO_MAX = 50
ENERGIA_TOTAL_DOCENCIO_MIN = 40
ENERGIA_TOTAL_DOCENCIO_MAX = 50
ENERGIA_TOTAL_TAREO_MIN = 35
ENERGIA_TOTAL_TAREO_MAX = 45
ENERGIA_TOTAL_HIBRIDO_MIN = 50
ENERGIA_TOTAL_HIBRIDO_MAX = 55
RESPONSABILIDAD_DOCENCIO_MIN = 15
RESPONSABILIDAD_DOCENCIO_MAX = 20
RESPONSABILIDAD_TAREO_MIN = 10
RESPONSABILIDAD_TAREO_MAX = 25
RESPONSABILIDAD_HIBRIDO_MIN = 15
RESPONSABILIDAD_HIBRIDO_MAX = 25

NIVEL_MAGICO_AUGUREY_MIN = 20
NIVEL_MAGICO_AUGUREY_MAX = 25
NIVEL_MAGICO_NIFFLER_MIN = 10
NIVEL_MAGICO_NIFFLER_MAX = 20
NIVEL_MAGICO_ERKLING_MIN = 30
NIVEL_MAGICO_ERKLING_MAX = 45
PROB_ESCAPE_AUGUREY = 0.2
PROB_ESCAPE_NIFFLER = 0.3
PROB_ESCAPE_ERKLING = 0.5
PROB_ENFERMAR_AUGUREY = 0.3
PROB_ENFERMAR_NIFFLER = 0.2
PROB_ENFERMAR_ERKLING = 0.3
SALUD_AUGUREY_MIN = 35
SALUD_AUGUREY_MAX = 45
SALUD_NIFFLER_MIN = 20
SALUD_NIFFLER_MAX = 30
SALUD_ERKLING_MIN = 50
SALUD_ERKLING_MAX = 60
LIMITE_HAMBRE_AUGUREY = 3
LIMITE_HAMBRE_NIFFLER = 2
LIMITE_HAMBRE_ERKLING = 2
NIVEL_AGRESVIDAD_AUGUREY = "inofensiva"
NIVEL_AGRESVIDAD_NIFFLER = "arisca"
NIVEL_AGRESVIDAD_ERKLING = "peligrosa"
CLEPTOMANIA_AUGUREY = 0
CLEPTOMANIA_ERKLING = 0
CLEPTOMANIA_NIFFLER_MIN = 5
CLEPTOMANIA_NIFFLER_MAX = 10

PRECIO_AUGEREY = 75
PRECIO_NIFFLER = 100
PRECIO_ERKLING = 125

PRECIO_TARTA_MELAZA = 10
PRECIO_HIGADO_DRAGON = 15
PRECIO_BUNUELOS_GUSARAJO = 3

GASTO_ALIMENTAR = 5
GASTO_RECUPERAR = 10
GASTO_SANAR = 8

DOCENCIO_AUMENTO_SALUD_TOTAL_CRIATURA = 5
HIBRIDO_AUMENTO_SALUD_ACTUAL_CRIATURA = 10
PROB_SALUD_TAREO = 0.7

EFECTO_HAMBRE_HAMBRIENTA = 15
EFECTO_HAMBRE_SATISFECHA = 0
EFECTO_AGRESIVIDAD_INOFENSIVA = 0
EFECTO_AGRESIVIDAD_ARISCA = 20
EFECTO_AGRESIVIDAD_PELIGROSA = 40

SALUD_TARTA_MELAZA = 15
SALUD_HIGADO_DRAGON = 10
SALUD_BUNUELO_GUSARAJO = 5

DOCENCIO_COSTO_RECUPERAR_CRIATURA = 7

COSTO_HABILIDAD_ESPECIAL = 15

PROB_RECHAZAR_BUNUELO = 0.35

PROB_CAMBIO_ARISCA_INOFENSIVA = 0.15

EFECTO_HAMBRE_MIN_ESCAPARSE = 0
EFECTO_HAMBRE_MAX_ESCAPARSE = 20

NIVEL_APROBACION_LICENCIA = 60
APROBACION_MAXIMA = 100

DIAS_SIN_COMER_AUGUREY = 3
DIAS_SIN_COMER_NIFFLER = 2
DIAS_SIN_COMER_ERKLING = 2

SALUD_MINIMA = 1

DISMINUCION_SALUD_POR_DIA_ENFERMO = 7
DISMINUCION_SALUD_POR_DIA_HAMBRE = 3

PROB_FISCALIZAR_ESCAPE = 0.5
PROB_FISCALIZAR_ENFERMEDAD = 0.7

MULTA_ESCAPE = 50
MULTA_ENFERMEDAD = 70
MULTA_SALUD_BAJA = 150