import os

RUTA_MAGIZOOLOGOS = os.path.join("magizoologos.csv")
RUTA_CRIATURAS = os.path.join("criaturas.csv")

SICKLES_INICIAL = 500

NIVEL_APROB_MAX = 100
NIVEL_APROB_MIN = 0

NIVEL_MAGICO_DOCENCIO_MIN = 40
NIVEL_MAGICO_DOCENCIO_MAX = 60
NIVEL_MAGICO_TAREO_MIN = 40
NIVEL_MAGICO_TAREO_MAX = 55
NIVEL_MAGICO_HIBRIDO_MIN = 35
NIVEL_MAGICO_HIBRIDO_MAX = 45
DESTREZA_DOCENCIO_MIN = 30
DESTREZA_DOCENCIO_MAX = 40
DESTREZA_TAREO_MIN = 40
DESTREZA_TAREO_MAX = 50
DESTREZA_HIBRIDO_MIN = 30
DESTREZA_HIBRIDO_MAX = 50
ENERGIA_TOTAL_DOCENCIO_MIN = 40
ENERGIA_TOTAL_DOCENCIO_MAX = 50
ENERGIA_TOTAL_TAREO_MIN = 35
ENERGIA_TOTAL_TAREO_MAX = 45
ENERGIA_TOTAL_HIBRIDO_MIN = 50
ENERGIA_TOTAL_HIBRIDO_MAX = 55
RESPONSABILIDAD_DOCENCIO_MIN = 15
RESPONSABILIDAD_DOCENCIO_MAX = 20
RESPONSABILIDAD_TAREO_MIN = 10
RESPONSABILIDAD_TAREO_MAX = 25
RESPONSABILIDAD_HIBRIDO_MIN = 15
RESPONSABILIDAD_HIBRIDO_MAX = 25

NIVEL_MAGICO_AUGUREY_MIN = 20
NIVEL_MAGICO_AUGUREY_MAX = 25
NIVEL_MAGICO_NIFFLER_MIN = 10
NIVEL_MAGICO_NIFFLER_MAX = 20
NIVEL_MAGICO_ERKLING_MIN = 30
NIVEL_MAGICO_ERKLING_MAX = 45
PROB_ESCAPE_AUGUREY = 0.2
PROB_ESCAPE_NIFFLER = 0.3
PROB_ESCAPE_ERKLING = 0.5
PROB_ENFERMAR_AUGUREY = 0.3
PROB_ENFERMAR_NIFFLER = 0.2
PROB_ENFERMAR_ERKLING = 0.3
SALUD_AUGUREY_MIN = 35
SALUD_AUGUREY_MAX = 45
SALUD_NIFFLER_MIN = 20
SALUD_NIFFLER_MAX = 30
SALUD_ERKLING_MIN = 50
SALUD_ERKLING_MAX = 60
LIMITE_HAMBRE_AUGUREY = 3
LIMITE_HAMBRE_NIFFLER = 2
LIMITE_HAMBRE_ERKLING = 2
NIVEL_AGRESVIDAD_AUGUREY = "inofensiva"
NIVEL_AGRESVIDAD_NIFFLER = "arisca"
NIVEL_AGRESVIDAD_ERKLING = "peligrosa"
CLEPTOMANIA_AUGUREY = 0
CLEPTOMANIA_ERKLING = 0
CLEPTOMANIA_NIFFLER_MIN = 5
CLEPTOMANIA_NIFFLER_MAX = 10

PRECIO_AUGEREY = 75
PRECIO_NIFFLER = 100
PRECIO_ERKLING = 125